# climate.yaml
# This is a yaml file containing the setup for my thermostat

# Thermostat
# Homeseer Node: 21
# Ref ID: 62 Name: Cooling Set Point
# Ref ID: 57 Name: Fan Mode
# Ref ID: 58 Name: Fan State
# Ref ID: 61 Name: Heating Set Point
# Ref ID: 59 Name: Mode
# Ref ID: 60 Name: Operating State
# Ref ID: 56 Name: Temperature

- platform: mqtt
  name: "Thermostat"
  unique_id: "Thermostat"
  fan_mode_command_topic: "CRUD-06/mcsMQTT/Thermostat/HVAC/Fan_Mode/Control"
  fan_modes:
    - "auto"
    - "on"
    - "circulation"
  fan_mode_state_topic: "CRUD-06/mcsMQTT/Thermostat/HVAC/Fan_Mode"
  mode_command_topic: "CRUD-06/mcsMQTT/Thermostat/HVAC/Mode/Control"
  modes:
    - "off"
    - "heat"
    - "cool"
    - "auto"
  mode_state_topic: "CRUD-06/mcsMQTT/Thermostat/HVAC/Mode"
  temperature_high_command_topic: "CRUD-06/mcsMQTT/Thermostat/HVAC/Heating_Setpoint/Control"
  temperature_high_state_topic: "CRUD-06/mcsMQTT/Thermostat/HVAC/Heating_Setpoint"
  temperature_low_command_topic: "CRUD-06/mcsMQTT/Thermostat/HVAC/Cooling_Setpoint/Control"
  temperature_low_state_topic: "CRUD-06/mcsMQTT/Thermostat/HVAC/Cooling_Setpoint"
  current_temperature_topic: "CRUD-06/mcsMQTT/Thermostat/HVAC/Temperature"
  temperature_unit: F
  