# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: 286ATS
  latitude: 30.351803
  longitude: -95.593334
  elevation: 79
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

# Google Calendar
google:
  client_id: 800864302205-2sjm1pqsvh50l8j52l02vid4ussarlrk.apps.googleusercontent.com
  client_secret: !secret gcalpw

# Text to speech
tts:
  - platform: google_translate

# Media Players available
media_player: !include media_players.yaml

# Notifications
notify: !include notify.yaml

# Groups
group: !include groups.yaml

# Automations
automation: !include automations.yaml

# Scripts
script: !include scripts.yaml

# Scenes
scene: !include scenes.yaml

# Switches (lights & appliances no Dimmers) setup in Homeseer
switch: !include switches.yaml

# Lights (Dimmers) setup in Homeseer
light: !include lights.yaml

# Door Locks setup in Homeseer
lock: !include locks.yaml

# Notification devices (battery level) setup in Homeseer
sensor: !include sensors.yaml

# Ceiling Fans setup in Homeseer
fan: !include fans.yaml

# Garage Door setup in Homeseer
cover: !include covers.yaml

# Thermostat setup in Homeseer
climate: !include climate.yaml

# Binary Sensors for Time Ranges intitially
binary_sensor: !include binary_sensors.yaml

#For Themes
frontend:
  themes: !include themes.yaml